version: "3.8"
services:
  angular:
    image: node:22.14-alpine
    volumes:
      - ./angular-app:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
  react:
    image: node:22.14-alpine
    volumes:
      - ./react-app:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
  vue:
    image: node:22.14-alpine
    volumes:
      - ./vue-app:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
