services:
  react-dev:
    image: node:22.14-alpine
    ports:
      - 3000:3000
    volumes:
      - ./react-app:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    networks:
      - dev-net

  vue-dev:
    image: node:22.14-alpine
    ports:
      - 3001:3000
    volumes:
      - ./vue-app:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    networks:
      - dev-net

  angular-dev:
    image: node:22.14-alpine
    ports:
      - 3002:3000
    volumes:
      - ./angular-app:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0 --poll 1000 --disable-host-check"
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
